CREATE TABLE IF NOT EXISTS users (
 id CHAR(36) PRIMARY KEY, email VARCHAR(254) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
CREATE TABLE IF NOT EXISTS sessions (
 token_hash CHAR(64) PRIMARY KEY, user_id CHAR(36) NOT NULL, expires_at DATETIME(3) NOT NULL,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX (expires_at)
);
CREATE TABLE IF NOT EXISTS login_limits (
 bucket CHAR(64) PRIMARY KEY, attempts INT NOT NULL DEFAULT 0, resets_at DATETIME(3) NOT NULL
);
CREATE TABLE IF NOT EXISTS projects (
 id VARCHAR(40) PRIMARY KEY, name VARCHAR(150) NOT NULL, site VARCHAR(150) NOT NULL,
 developer VARCHAR(200) NOT NULL, launch_window VARCHAR(100) NOT NULL,
 units VARCHAR(30) NOT NULL DEFAULT '', details TEXT NOT NULL, folder_url VARCHAR(2048) NOT NULL DEFAULT '',
 client JSON NOT NULL, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);
CREATE TABLE IF NOT EXISTS designs (
 id CHAR(36) PRIMARY KEY, project_id VARCHAR(40) NOT NULL,
 name VARCHAR(100) NOT NULL, format VARCHAR(40) NOT NULL, source_url VARCHAR(2048) NOT NULL DEFAULT '',
 status ENUM('Unused','Active','Suspended') NOT NULL DEFAULT 'Unused',
 revision INT NOT NULL DEFAULT 0, published_revision INT NULL, published_path VARCHAR(255) NULL,
 published_at DATETIME(3) NULL, updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
 FOREIGN KEY (project_id) REFERENCES projects(id), INDEX (project_id)
);
CREATE TABLE IF NOT EXISTS revisions (
 design_id CHAR(36) NOT NULL, revision INT NOT NULL, storage_path VARCHAR(255) NOT NULL,
 entry_point VARCHAR(1024) NOT NULL, manifest JSON NOT NULL, byte_size BIGINT NOT NULL,
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 PRIMARY KEY (design_id, revision), FOREIGN KEY (design_id) REFERENCES designs(id) ON DELETE CASCADE
);
